name = "wematatapp"
main = "functions/_worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "wemetatapp"
database_id = "6fde8bcf-8ab2-4a5c-950e-1f9dbe06eb8a"
